spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: test
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true